### ISSUE TITLE
Laravel 11?

### ISSUE THREAD

**Issue by kristenzirkler** [intonate/laravel-mandrill-driver#10]
Will you be adding support for laravel 11?

**Comment by kristenzirkler** [comment]
@scrubmx Sorry to be a pest do you know IF you will update to be compatible with Laravel 11 and if so when you think it will be complete? We would love to continue to use your resource but totally understand if this is not going to be supported. Thanks!

**Comment by scrubmx** [comment]
@kristenzirkler I'll release a new version with support for Laravel 11 later today.

**Comment by scrubmx** [comment]
Added support for Laravel 11 in https://github.com/intonate/laravel-mandrill-driver/releases/tag/v4.0
