### ISSUE TITLE
Package for laravel 7 not found, please fix it :(

### ISSUE THREAD

**Issue by cyongkypranowo** [intonate/laravel-mandrill-driver#3]
Package for laravel 7 not found, please fix it :( my project using mandrill

**Comment by kusmayadi** [comment]
+1

Could not find package intonate/laravel-mandrill-driver in a version matching 1.2.0

**Comment by scrubmx** [comment]
This is resolved now https://github.com/intonate/laravel-mandrill-driver/releases/tag/1.2.1
