### ISSUE TITLE
Laravel 10?

### ISSUE THREAD

**Issue by kristenzirkler** [intonate/laravel-mandrill-driver#9]
Will you be supporting Laravel 10? If so, do you have an ETA?

**Comment by scrubmx** [comment]
Added support for Laravel 10 in https://github.com/intonate/laravel-mandrill-driver/releases/tag/3.1.0

Just make sure to require version `^3.1` as indicated on the [README](https://github.com/intonate/laravel-mandrill-driver/blob/master/README.md#versions).
